# Generated by Django 5.0.3 on 2026-03-21 11:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteOilRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_number", models.CharField(max_length=30, unique=True)),
                ("vendor_name", models.CharField(max_length=200)),
                (
                    "vendor_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quantity_litres",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("oil_type", models.CharField(max_length=100)),
                ("collection_date", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                ("attachment_paths", models.JSONField(default=list)),
                (
                    "current_stage",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("disposal_deadline", models.DateField()),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                            ("completed", "Completed"),
                        ],
                        default="green",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_waste_oil_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_department",
                    models.ForeignKey(
                        blank=True,
                        db_column="current_department_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_waste_oil_records",
                        to="accounts.department",
                    ),
                ),
                (
                    "current_holder",
                    models.ForeignKey(
                        blank=True,
                        db_column="current_holder_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_waste_oil_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "waste_oil_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["current_stage"], name="waste_oil_r_current_4ca22f_idx"
                    ),
                    models.Index(
                        fields=["alert_level"], name="waste_oil_r_alert_l_5b268c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="waste_oil_r_created_e642aa_idx"
                    ),
                    models.Index(
                        fields=["collection_date"],
                        name="waste_oil_r_collect_1f80c0_idx",
                    ),
                    models.Index(
                        fields=["disposal_deadline"],
                        name="waste_oil_r_disposa_92fbb6_idx",
                    ),
                ],
            },
        ),
    ]
