# Generated by Django 5.0.3 on 2026-04-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_vendor_and_inventory_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="wasteoilrecord",
            new_name="waste_oil_r_entry_d_4f7714_idx",
            old_name="waste_oil_r_entry_d_7b8f1e_idx",
        ),
        migrations.RenameIndex(
            model_name="wasteoilrecord",
            new_name="waste_oil_r_due_dat_d6e41f_idx",
            old_name="waste_oil_r_due_dat_9c2a4b_idx",
        ),
        migrations.AlterField(
            model_name="wasteoilrecord",
            name="alert_level",
            field=models.CharField(
                choices=[
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                    ("completed", "Completed"),
                ],
                default="green",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="wasteoilrecord",
            name="product_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="wasteoilrecord",
            name="product_type",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="wasteoilrecord",
            name="unit",
            field=models.CharField(max_length=40),
        ),
    ]
