# Generated by Django 5.1.15 on 2026-08-20 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_rename_departments_workflo_7986f9_idx_departments_workflo_7f0e07_idx",
        ),
        ("records", "0005_remove_vendor_contact_and_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wasteoilrecord",
            index=models.Index(
                fields=["current_stage", "is_locked"],
                name="waste_oil_r_current_951e76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wasteoilrecord",
            index=models.Index(
                fields=["current_holder", "alert_level"],
                name="waste_oil_r_current_c192cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wasteoilrecord",
            index=models.Index(
                fields=["current_department", "-created_at"],
                name="waste_oil_r_current_cb1402_idx",
            ),
        ),
    ]
