# Generated by Django 5.1.15 on 2026-06-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='kind',
            field=models.CharField(choices=[('record_forwarded', 'Record forwarded'), ('record_returned', 'Record returned'), ('record_completed', 'Record completed'), ('sla_alert', 'SLA alert'), ('monthly_report', 'Monthly report'), ('welcome_employee', 'Welcome'), ('custom_broadcast', 'Broadcast')], max_length=40),
        ),
    ]
