# Generated by Django 5.0.3 on 2026-04-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_audit_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("EDIT", "Edit"),
                    ("FORWARD", "Forward"),
                    ("RETURN", "Return"),
                    ("APPROVE", "Approve"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("EXPORT", "Export"),
                    ("ALERT_SENT", "Alert sent"),
                    ("DELETE", "Delete"),
                ],
                max_length=30,
            ),
        ),
    ]
