# Generated by Django 5.0.3 on 2026-03-21 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.CharField(max_length=10)),
                ("sent_to", models.JSONField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "record",
                    models.ForeignKey(
                        db_column="record_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_notifications",
                        to="records.wasteoilrecord",
                    ),
                ),
            ],
            options={
                "db_table": "alert_notifications",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["record"], name="alert_notif_record__6e28b4_idx"
                    ),
                    models.Index(
                        fields=["sent_at"], name="alert_notif_sent_at_798d01_idx"
                    ),
                    models.Index(fields=["level"], name="alert_notif_level_43f222_idx"),
                ],
            },
        ),
    ]
