# Generated by Django 5.0.3 on 2026-03-21 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StageTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_stage", models.IntegerField()),
                ("to_stage", models.IntegerField()),
                (
                    "transition_type",
                    models.CharField(
                        choices=[("forward", "Forward"), ("return", "Return")],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_department",
                    models.ForeignKey(
                        blank=True,
                        db_column="from_department_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_from",
                        to="accounts.department",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        db_column="record_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_transitions",
                        to="records.wasteoilrecord",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        blank=True,
                        db_column="to_department_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_to",
                        to="accounts.department",
                    ),
                ),
                (
                    "transitioned_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="transitioned_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_transitions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stage_transitions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["record"], name="stage_trans_record__784d9f_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="stage_trans_timesta_adbc42_idx"
                    ),
                ],
            },
        ),
    ]
