# Generated by Django 5.0.3 on 2026-04-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_stagetransition_sequence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stagetransition",
            options={"ordering": ["sequence"]},
        ),
        migrations.RenameIndex(
            model_name="stagetransition",
            new_name="stage_trans_record__4475a5_idx",
            old_name="stage_trans_record_s_2a9c1e_idx",
        ),
    ]
