# Generated by Django 5.1.15 on 2026-08-20 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_rename_departments_workflo_7986f9_idx_departments_workflo_7f0e07_idx",
        ),
        ("records", "0006_perf_list_indexes"),
        ("workflow", "0004_stagetransition_to_holder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stagetransition",
            index=models.Index(
                fields=["transitioned_by", "transition_type", "record"],
                name="stage_trans_transit_a2b20e_idx",
            ),
        ),
    ]
