# Generated by Django 5.0.3 on 2026-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_seed_pipeline_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="If true, API access is limited until the user changes password (GM-created accounts).",
            ),
        ),
    ]
