# Generated by Django 5.0.3 on 2026-05-09 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_department_workflow_layer"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAuthSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "refresh_jti",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "client_kind",
                    models.CharField(
                        choices=[
                            ("tauri", "Desktop (Tauri)"),
                            ("expo", "Mobile (Expo)"),
                            ("web", "Web browser"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("device_label", models.CharField(blank=True, max_length=200)),
                ("app_version", models.CharField(blank=True, max_length=80)),
                ("platform", models.CharField(blank=True, max_length=120)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_auth_sessions",
            },
        ),
        migrations.AddField(
            model_name="userauthsession",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userauthsession",
            index=models.Index(
                fields=["user", "-last_seen_at"], name="user_auth_s_user_id_039ea3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userauthsession",
            index=models.Index(
                fields=["user", "revoked_at"], name="user_auth_s_user_id_717f3c_idx"
            ),
        ),
    ]
