# Generated by Django 5.0.3 on 2026-05-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_auth_session_and_notifications"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="department",
            new_name="departments_workflo_7f0e07_idx",
            old_name="departments_workflo_7986f9_idx",
        ),
    ]
